# Generated by Django 5.0.6 on 2024-06-25 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(20)])),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
